# Generated by Django 3.0.4 on 2020-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id_like', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
    ]
