# Generated by Django 2.2.6 on 2020-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='advanced_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_reference', models.CharField(max_length=250)),
                ('avatar', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'advanced_user',
                'managed': False,
            },
        ),
    ]
